######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 4 19:49:18 2013
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += functions.h recognizer.h
SOURCES += recognizertest.cpp recognizer.cpp

INCLUDEPATH += ../..
DEPENDPATH += $$INCLUDEPATH
